case1 = {
    'Name': 'Aarhus',
    'Municipalities': ['Aarhus'],
    'Plot_range': (128, 180),
    'Fit_range': (135, 165),
    'save_plots': False,
    'SystError': 0.0005,
    'scale_test': 3000,
    'dayLockdown': 157,
    'doSIRModelPlot': True,
    'doSEIRModelPlot': True,
    'doFitSIRinit': True,
    'doFitSIR': True,
    'doFitSEIR': True,
    'verbose_plot': True,
    'nI0_plot': 5.0,
    'beta0_plot': 0.75,
    'beta1_plot': 0.13,
    'lambdaE_plot': 1.0,
    'lambdaI_plot': 1.0,
    'Fit_EndDay_delay': 2
}

case2 = {
    'Name': 'Odense',
    'Municipalities': ['Odense'],
    'Plot_range': (150, 200),
    'Fit_range': (175, 190),
    'save_plots': False,
    'SystError': 0.0005,
    'scale_test': 1500,
    'dayLockdown': 185,
    'doSIRModelPlot': True,
    'doSEIRModelPlot': True,
    'doFitSIRinit': True,
    'doFitSIR': True,
    'doFitSEIR': True,
    'verbose_plot': True,
    'nI0_plot': 5.0,
    'beta0_plot': 0.75,
    'beta1_plot': 0.13,
    'lambdaE_plot': 1.0,
    'lambdaI_plot': 1.0,
    'Fit_EndDay_delay': -1
}

case3 = {
    'Name': 'Copenhagen and Frederiksberg',
    'Municipalities': ['Copenhagen', 'Frederiksberg'],
    'Plot_range': (150, 208),
    'Fit_range': (175, 208),
    'save_plots': True,
    'SystError': 0.0005,
    'scale_test': 5000,
    'dayLockdown': 200.5,
    'doSIRModelPlot': True,
    'doSEIRModelPlot': True,
    'doFitSIRinit': True,
    'doFitSIR': True,
    'doFitSEIR': True,
    'verbose_plot': True,
    'nI0_plot': 5.0,
    'beta0_plot': 0.75,
    'beta1_plot': 0.13,
    'lambdaE_plot': 1.0,
    'lambdaI_plot': 1.0,
    'Fit_EndDay_delay': 3
}

case4 = {
    'Name': 'Nordjylland',
    'Municipalities': ["Aalborg", "Jammerbugt", "Brønderslev", "Hjørring", "Frederikshavn"],
    'Plot_range': (175, 208),
    'Fit_range': (183, 205),
    'save_plots': True,
    'SystError': 0.0005,
    'scale_test': 5000,
    'dayLockdown': 198,
    'doSIRModelPlot': True,
    'doSEIRModelPlot': True,
    'doFitSIRinit': True,
    'doFitSIR': True,
    'doFitSEIR': True,
    'verbose_plot': True,
    'nI0_plot': 5.0,
    'beta0_plot': 0.75,
    'beta1_plot': 0.13,
    'lambdaE_plot': 1.0,
    'lambdaI_plot': 1.0,
    'Fit_EndDay_delay': 5
}

case5 = {
    'Name': 'Vestegnen',
    'Municipalities': ["Albertslund", "Ballerup", "Brøndby", "Vallensbæk", "Hvidovre", "Hvidovre", "Rødovre", "Glostrup", "Ishøj", "Høje-Taastrup"],
    'Plot_range': (150, 206),
    'Fit_range': (178, 206),
    'save_plots': True,
    'SystError': 0.0005,
    'scale_test': 2500,
    'dayLockdown': 185,
    'doSIRModelPlot': False,
    'doSEIRModelPlot': False,
    'doFitSIRinit': True,
    'doFitSIR': True,
    'doFitSEIR': True,
    'verbose_plot': True,
    'nI0_plot': 5.0,
    'beta0_plot': 0.75,
    'beta1_plot': 0.32,
    'lambdaE_plot': 1.0,
    'lambdaI_plot': 1.0,
    'Fit_EndDay_delay': 4
}

case6 = {
    'Name': 'Sønderjylland',
    'Municipalities': ["Tønder", "Esbjerg", "Kolding", "Fredericia", "Vejen", "Aabenraa", "Sønderborg"],
    'Plot_range': (150, 207),
    'Fit_range': (185, 204),
    'save_plots': False,
    'SystError': 0.0005,
    'scale_test': 2500,
    'dayLockdown': 204,
    'doSIRModelPlot': False,
    'doSEIRModelPlot': False,
    'doFitSIRinit': True,
    'doFitSIR': True,
    'doFitSEIR': True,
    'verbose_plot': True,
    'nI0_plot': 5.0,
    'beta0_plot': 0.75,
    'beta1_plot': 0.32,
    'lambdaE_plot': 1.0,
    'lambdaI_plot': 1.0,
    'Fit_EndDay_delay': 2
}

load_case = case1
